namespace DD.CBU.Compute.Api.Contracts.Server
{
    using Network20;
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("copyServer", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class CopyServerType
    {

        /// <remarks/>
        public CopyServerNicType targetPrimaryNic;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tagById")]
        public ApplyTagByIdType[] tagById;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public ApplyTagType[] tag;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceServerId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    public partial class CopyServerNicType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string vlanId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string privateIpv4;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool preserveMacAddress;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preserveMacAddressSpecified;
    }
}