//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DD.CBU.Compute.Api.Contracts.Network20
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("enableSnapshotService", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class EnableSnapshotServiceType
    {

        private string servicePlanField;

        private string windowIdField;

        private bool initiateManualSnapshotField;

        private EnableSnapshotServiceTypePreSnapshotScript preSnapshotScriptField;

        private EnableSnapshotServiceTypePostSnapshotScript postSnapshotScriptField;

        private EnableSnapshotServiceTypeServerCredentials serverCredentialsField;

        private string replicationTargetDatacenterIdField;

        private string serverIdField;

        /// <remarks/>
        public string servicePlan
        {
            get
            {
                return this.servicePlanField;
            }
            set
            {
                this.servicePlanField = value;
            }
        }

        /// <remarks/>
        public string windowId
        {
            get
            {
                return this.windowIdField;
            }
            set
            {
                this.windowIdField = value;
            }
        }

        /// <remarks/>
        public bool initiateManualSnapshot
        {
            get
            {
                return this.initiateManualSnapshotField;
            }
            set
            {
                this.initiateManualSnapshotField = value;
            }
        }

        /// <remarks/>
        public EnableSnapshotServiceTypePreSnapshotScript preSnapshotScript
        {
            get
            {
                return this.preSnapshotScriptField;
            }
            set
            {
                this.preSnapshotScriptField = value;
            }
        }

        /// <remarks/>
        public EnableSnapshotServiceTypePostSnapshotScript postSnapshotScript
        {
            get
            {
                return this.postSnapshotScriptField;
            }
            set
            {
                this.postSnapshotScriptField = value;
            }
        }

        /// <remarks/>
        public EnableSnapshotServiceTypeServerCredentials serverCredentials
        {
            get
            {
                return this.serverCredentialsField;
            }
            set
            {
                this.serverCredentialsField = value;
            }
        }

        /// <remarks/>
        public string replicationTargetDatacenterId
        {
            get
            {
                return this.replicationTargetDatacenterIdField;
            }
            set
            {
                this.replicationTargetDatacenterIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serverId
        {
            get
            {
                return this.serverIdField;
            }
            set
            {
                this.serverIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class EnableSnapshotServiceTypePreSnapshotScript
    {

        private string pathField;

        private string descriptionField;

        private int timeoutSecondsField;

        private bool timeoutSecondsFieldSpecified;

        private string onFailureField;

        /// <remarks/>
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int timeoutSeconds
        {
            get
            {
                return this.timeoutSecondsField;
            }
            set
            {
                this.timeoutSecondsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSecondsSpecified
        {
            get
            {
                return this.timeoutSecondsFieldSpecified;
            }
            set
            {
                this.timeoutSecondsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string onFailure
        {
            get
            {
                return this.onFailureField;
            }
            set
            {
                this.onFailureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class EnableSnapshotServiceTypePostSnapshotScript
    {

        private string pathField;

        private string descriptionField;

        /// <remarks/>
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class EnableSnapshotServiceTypeServerCredentials
    {

        private string usernameField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
}