//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace DD.CBU.Compute.Api.Contracts.Organization {
    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
    [System.SerializableAttribute ()]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute (Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class organization {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string homeGeoName;

        /// <remarks/>
        public string homeGeoApiHost;

        /// <remarks/>
        public string homeGeoId;

        /// <remarks/>
        public bool verified;

        /// <remarks/>
        public organizationVpn vpn;

        /// <remarks/>
        public bool uiMfa;

        /// <remarks/>
        public System.DateTime createTime;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute ()]
        public string id;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("xsd", "4.6.1055.0")]
    [System.SerializableAttribute ()]
    [System.Diagnostics.DebuggerStepThroughAttribute ()]
    [System.ComponentModel.DesignerCategoryAttribute ("code")]
    [System.Xml.Serialization.XmlTypeAttribute (AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
    public partial class organizationVpn {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute ()]
        public string vpnAccess;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute ()]
        public string state;
    }
}