//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DD.CBU.Compute.Api.Contracts.Network20;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
public partial class snapshots
{

    private SnapshotType[] snapshotField;

    private int pageNumberField;

    private bool pageNumberFieldSpecified;

    private int pageCountField;

    private bool pageCountFieldSpecified;

    private int totalCountField;

    private bool totalCountFieldSpecified;

    private int pageSizeField;

    private bool pageSizeFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("snapshot")]
    public SnapshotType[] snapshot
    {
        get
        {
            return this.snapshotField;
        }
        set
        {
            this.snapshotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int pageNumber
    {
        get
        {
            return this.pageNumberField;
        }
        set
        {
            this.pageNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pageNumberSpecified
    {
        get
        {
            return this.pageNumberFieldSpecified;
        }
        set
        {
            this.pageNumberFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int pageCount
    {
        get
        {
            return this.pageCountField;
        }
        set
        {
            this.pageCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pageCountSpecified
    {
        get
        {
            return this.pageCountFieldSpecified;
        }
        set
        {
            this.pageCountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int totalCount
    {
        get
        {
            return this.totalCountField;
        }
        set
        {
            this.totalCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalCountSpecified
    {
        get
        {
            return this.totalCountFieldSpecified;
        }
        set
        {
            this.totalCountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int pageSize
    {
        get
        {
            return this.pageSizeField;
        }
        set
        {
            this.pageSizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pageSizeSpecified
    {
        get
        {
            return this.pageSizeFieldSpecified;
        }
        set
        {
            this.pageSizeFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigType
{

    private SnapshotServerConfigTypeCluster clusterField;

    private SnapshotServerConfigTypeCpu cpuField;

    private uint memoryGbField;

    private SnapshotServerConfigTypeScsiController[] scsiControllerField;

    private SnapshotServerConfigTypeSataController[] sataControllerField;

    private SnapshotServerConfigTypeIdeController[] ideControllerField;

    private SnapshotServerConfigTypeFloppy[] floppyField;

    private SnapshotServerConfigTypeNetworkInfo networkInfoField;

    private string[] softwareLabelField;

    private SnapshotServerConfigTypeGuest guestField;

    private string virtualHardwareVersionField;

    /// <remarks/>
    public SnapshotServerConfigTypeCluster cluster
    {
        get
        {
            return this.clusterField;
        }
        set
        {
            this.clusterField = value;
        }
    }

    /// <remarks/>
    public SnapshotServerConfigTypeCpu cpu
    {
        get
        {
            return this.cpuField;
        }
        set
        {
            this.cpuField = value;
        }
    }

    /// <remarks/>
    public uint memoryGb
    {
        get
        {
            return this.memoryGbField;
        }
        set
        {
            this.memoryGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("scsiController")]
    public SnapshotServerConfigTypeScsiController[] scsiController
    {
        get
        {
            return this.scsiControllerField;
        }
        set
        {
            this.scsiControllerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sataController")]
    public SnapshotServerConfigTypeSataController[] sataController
    {
        get
        {
            return this.sataControllerField;
        }
        set
        {
            this.sataControllerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ideController")]
    public SnapshotServerConfigTypeIdeController[] ideController
    {
        get
        {
            return this.ideControllerField;
        }
        set
        {
            this.ideControllerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("floppy")]
    public SnapshotServerConfigTypeFloppy[] floppy
    {
        get
        {
            return this.floppyField;
        }
        set
        {
            this.floppyField = value;
        }
    }

    /// <remarks/>
    public SnapshotServerConfigTypeNetworkInfo networkInfo
    {
        get
        {
            return this.networkInfoField;
        }
        set
        {
            this.networkInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("softwareLabel")]
    public string[] softwareLabel
    {
        get
        {
            return this.softwareLabelField;
        }
        set
        {
            this.softwareLabelField = value;
        }
    }

    /// <remarks/>
    public SnapshotServerConfigTypeGuest guest
    {
        get
        {
            return this.guestField;
        }
        set
        {
            this.guestField = value;
        }
    }

    /// <remarks/>
    public string virtualHardwareVersion
    {
        get
        {
            return this.virtualHardwareVersionField;
        }
        set
        {
            this.virtualHardwareVersionField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeCluster
{

    private string idField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeCpu
{

    private uint countField;

    private bool countFieldSpecified;

    private string speedField;

    private uint coresPerSocketField;

    private bool coresPerSocketFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countSpecified
    {
        get
        {
            return this.countFieldSpecified;
        }
        set
        {
            this.countFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint coresPerSocket
    {
        get
        {
            return this.coresPerSocketField;
        }
        set
        {
            this.coresPerSocketField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool coresPerSocketSpecified
    {
        get
        {
            return this.coresPerSocketFieldSpecified;
        }
        set
        {
            this.coresPerSocketFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeScsiController
{

    private SnapshotServerConfigTypeScsiControllerDisk[] diskField;

    private string idField;

    private string adapterTypeField;

    private string stateField;

    private int busNumberField;

    private bool busNumberFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("disk")]
    public SnapshotServerConfigTypeScsiControllerDisk[] disk
    {
        get
        {
            return this.diskField;
        }
        set
        {
            this.diskField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string adapterType
    {
        get
        {
            return this.adapterTypeField;
        }
        set
        {
            this.adapterTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int busNumber
    {
        get
        {
            return this.busNumberField;
        }
        set
        {
            this.busNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool busNumberSpecified
    {
        get
        {
            return this.busNumberFieldSpecified;
        }
        set
        {
            this.busNumberFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeScsiControllerDisk
{

    private string idField;

    private int sizeGbField;

    private string speedField;

    private int iopsField;

    private bool iopsFieldSpecified;

    private string driveTypeField;

    private string stateField;

    private int scsiIdField;

    private bool scsiIdFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int iops
    {
        get
        {
            return this.iopsField;
        }
        set
        {
            this.iopsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool iopsSpecified
    {
        get
        {
            return this.iopsFieldSpecified;
        }
        set
        {
            this.iopsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string driveType
    {
        get
        {
            return this.driveTypeField;
        }
        set
        {
            this.driveTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int scsiId
    {
        get
        {
            return this.scsiIdField;
        }
        set
        {
            this.scsiIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool scsiIdSpecified
    {
        get
        {
            return this.scsiIdFieldSpecified;
        }
        set
        {
            this.scsiIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeSataController
{

    private object[] itemsField;

    private string idField;

    private string adapterTypeField;

    private string stateField;

    private int busNumberField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device", typeof(SnapshotServerConfigTypeSataControllerDevice))]
    [System.Xml.Serialization.XmlElementAttribute("disk", typeof(SnapshotServerConfigTypeSataControllerDisk))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string adapterType
    {
        get
        {
            return this.adapterTypeField;
        }
        set
        {
            this.adapterTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int busNumber
    {
        get
        {
            return this.busNumberField;
        }
        set
        {
            this.busNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeSataControllerDevice
{

    private string idField;

    private string typeField;

    private int sizeGbField;

    private bool sizeGbFieldSpecified;

    private string fileNameField;

    private string driveTypeField;

    private string stateField;

    private int sataIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeGbSpecified
    {
        get
        {
            return this.sizeGbFieldSpecified;
        }
        set
        {
            this.sizeGbFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string driveType
    {
        get
        {
            return this.driveTypeField;
        }
        set
        {
            this.driveTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sataId
    {
        get
        {
            return this.sataIdField;
        }
        set
        {
            this.sataIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeSataControllerDisk
{

    private string idField;

    private int sizeGbField;

    private string speedField;

    private int iopsField;

    private bool iopsFieldSpecified;

    private string driveTypeField;

    private string stateField;

    private int sataIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int iops
    {
        get
        {
            return this.iopsField;
        }
        set
        {
            this.iopsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool iopsSpecified
    {
        get
        {
            return this.iopsFieldSpecified;
        }
        set
        {
            this.iopsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string driveType
    {
        get
        {
            return this.driveTypeField;
        }
        set
        {
            this.driveTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sataId
    {
        get
        {
            return this.sataIdField;
        }
        set
        {
            this.sataIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeIdeController
{

    private object[] itemsField;

    private string idField;

    private string adapterTypeField;

    private string stateField;

    private int channelField;

    private bool channelFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device", typeof(SnapshotServerConfigTypeIdeControllerDevice))]
    [System.Xml.Serialization.XmlElementAttribute("disk", typeof(SnapshotServerConfigTypeIdeControllerDisk))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string adapterType
    {
        get
        {
            return this.adapterTypeField;
        }
        set
        {
            this.adapterTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int channel
    {
        get
        {
            return this.channelField;
        }
        set
        {
            this.channelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool channelSpecified
    {
        get
        {
            return this.channelFieldSpecified;
        }
        set
        {
            this.channelFieldSpecified = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeIdeControllerDevice
{

    private string idField;

    private string typeField;

    private int sizeGbField;

    private bool sizeGbFieldSpecified;

    private string fileNameField;

    private string driveTypeField;

    private string stateField;

    private int slotField;

    private bool slotFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeGbSpecified
    {
        get
        {
            return this.sizeGbFieldSpecified;
        }
        set
        {
            this.sizeGbFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string driveType
    {
        get
        {
            return this.driveTypeField;
        }
        set
        {
            this.driveTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int slot
    {
        get
        {
            return this.slotField;
        }
        set
        {
            this.slotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool slotSpecified
    {
        get
        {
            return this.slotFieldSpecified;
        }
        set
        {
            this.slotFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeIdeControllerDisk
{

    private string idField;

    private int sizeGbField;

    private string speedField;

    private int iopsField;

    private bool iopsFieldSpecified;

    private string driveTypeField;

    private string stateField;

    private int slotField;

    private bool slotFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string speed
    {
        get
        {
            return this.speedField;
        }
        set
        {
            this.speedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int iops
    {
        get
        {
            return this.iopsField;
        }
        set
        {
            this.iopsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool iopsSpecified
    {
        get
        {
            return this.iopsFieldSpecified;
        }
        set
        {
            this.iopsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string driveType
    {
        get
        {
            return this.driveTypeField;
        }
        set
        {
            this.driveTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int slot
    {
        get
        {
            return this.slotField;
        }
        set
        {
            this.slotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool slotSpecified
    {
        get
        {
            return this.slotFieldSpecified;
        }
        set
        {
            this.slotFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeFloppy
{

    private string idField;

    private int driveNumberField;

    private int sizeGbField;

    private bool sizeGbFieldSpecified;

    private string fileNameField;

    private string stateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int driveNumber
    {
        get
        {
            return this.driveNumberField;
        }
        set
        {
            this.driveNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sizeGb
    {
        get
        {
            return this.sizeGbField;
        }
        set
        {
            this.sizeGbField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeGbSpecified
    {
        get
        {
            return this.sizeGbFieldSpecified;
        }
        set
        {
            this.sizeGbFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileName
    {
        get
        {
            return this.fileNameField;
        }
        set
        {
            this.fileNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeNetworkInfo
{

    private SnapshotServerConfigTypeNetworkInfoPrimaryNic primaryNicField;

    private SnapshotServerConfigTypeNetworkInfoAdditionalNic[] additionalNicField;

    private string networkDomainIdField;

    private string networkDomainNameField;

    /// <remarks/>
    public SnapshotServerConfigTypeNetworkInfoPrimaryNic primaryNic
    {
        get
        {
            return this.primaryNicField;
        }
        set
        {
            this.primaryNicField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("additionalNic")]
    public SnapshotServerConfigTypeNetworkInfoAdditionalNic[] additionalNic
    {
        get
        {
            return this.additionalNicField;
        }
        set
        {
            this.additionalNicField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkDomainId
    {
        get
        {
            return this.networkDomainIdField;
        }
        set
        {
            this.networkDomainIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkDomainName
    {
        get
        {
            return this.networkDomainNameField;
        }
        set
        {
            this.networkDomainNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeNetworkInfoPrimaryNic
{

    private string idField;

    private string privateIpv4Field;

    private string ipv6Field;

    private string vlanIdField;

    private string vlanNameField;

    private string networkAdapterField;

    private bool connectedField;

    private int keyField;

    private string stateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string privateIpv4
    {
        get
        {
            return this.privateIpv4Field;
        }
        set
        {
            this.privateIpv4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ipv6
    {
        get
        {
            return this.ipv6Field;
        }
        set
        {
            this.ipv6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vlanId
    {
        get
        {
            return this.vlanIdField;
        }
        set
        {
            this.vlanIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vlanName
    {
        get
        {
            return this.vlanNameField;
        }
        set
        {
            this.vlanNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkAdapter
    {
        get
        {
            return this.networkAdapterField;
        }
        set
        {
            this.networkAdapterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool connected
    {
        get
        {
            return this.connectedField;
        }
        set
        {
            this.connectedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeNetworkInfoAdditionalNic
{

    private string idField;

    private string privateIpv4Field;

    private string ipv6Field;

    private string vlanIdField;

    private string vlanNameField;

    private string networkAdapterField;

    private bool connectedField;

    private int keyField;

    private string stateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string privateIpv4
    {
        get
        {
            return this.privateIpv4Field;
        }
        set
        {
            this.privateIpv4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ipv6
    {
        get
        {
            return this.ipv6Field;
        }
        set
        {
            this.ipv6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vlanId
    {
        get
        {
            return this.vlanIdField;
        }
        set
        {
            this.vlanIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vlanName
    {
        get
        {
            return this.vlanNameField;
        }
        set
        {
            this.vlanNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string networkAdapter
    {
        get
        {
            return this.networkAdapterField;
        }
        set
        {
            this.networkAdapterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool connected
    {
        get
        {
            return this.connectedField;
        }
        set
        {
            this.connectedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeGuest
{

    private SnapshotServerConfigTypeGuestOperatingSystem operatingSystemField;

    private bool osCustomizationField;

    private bool osCustomizationFieldSpecified;

    /// <remarks/>
    public SnapshotServerConfigTypeGuestOperatingSystem operatingSystem
    {
        get
        {
            return this.operatingSystemField;
        }
        set
        {
            this.operatingSystemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool osCustomization
    {
        get
        {
            return this.osCustomizationField;
        }
        set
        {
            this.osCustomizationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool osCustomizationSpecified
    {
        get
        {
            return this.osCustomizationFieldSpecified;
        }
        set
        {
            this.osCustomizationFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:didata.com:api:cloud:types")]
public partial class SnapshotServerConfigTypeGuestOperatingSystem
{

    private string idField;

    private string displayNameField;

    private string familyField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName
    {
        get
        {
            return this.displayNameField;
        }
        set
        {
            this.displayNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string family
    {
        get
        {
            return this.familyField;
        }
        set
        {
            this.familyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
[System.Xml.Serialization.XmlRootAttribute("snapshot", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
public partial class SnapshotType
{

    private System.DateTime startTimeField;

    private bool startTimeFieldSpecified;

    private System.DateTime endTimeField;

    private bool endTimeFieldSpecified;

    private System.DateTime expiryTimeField;

    private bool expiryTimeFieldSpecified;

    private string typeField;

    private string datacenterIdField;

    private string descriptionField;

    private string consistencyLevelField;

    private string indexStateField;

    private SnapshotServerConfigType serverConfigField;

    private string stateField;

    private ProgressType progressField;

    private System.DateTime createTimeField;

    private bool createTimeFieldSpecified;

    private string idField;

    private bool replicaField;

    /// <remarks/>
    public System.DateTime startTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified
    {
        get
        {
            return this.startTimeFieldSpecified;
        }
        set
        {
            this.startTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    public System.DateTime endTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified
    {
        get
        {
            return this.endTimeFieldSpecified;
        }
        set
        {
            this.endTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    public System.DateTime expiryTime
    {
        get
        {
            return this.expiryTimeField;
        }
        set
        {
            this.expiryTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expiryTimeSpecified
    {
        get
        {
            return this.expiryTimeFieldSpecified;
        }
        set
        {
            this.expiryTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string datacenterId
    {
        get
        {
            return this.datacenterIdField;
        }
        set
        {
            this.datacenterIdField = value;
        }
    }

    /// <remarks/>
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string consistencyLevel
    {
        get
        {
            return this.consistencyLevelField;
        }
        set
        {
            this.consistencyLevelField = value;
        }
    }

    /// <remarks/>
    public string indexState
    {
        get
        {
            return this.indexStateField;
        }
        set
        {
            this.indexStateField = value;
        }
    }

    /// <remarks/>
    public SnapshotServerConfigType serverConfig
    {
        get
        {
            return this.serverConfigField;
        }
        set
        {
            this.serverConfigField = value;
        }
    }

    /// <remarks/>
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    public ProgressType progress
    {
        get
        {
            return this.progressField;
        }
        set
        {
            this.progressField = value;
        }
    }

    /// <remarks/>
    public System.DateTime createTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createTimeSpecified
    {
        get
        {
            return this.createTimeFieldSpecified;
        }
        set
        {
            this.createTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool replica
    {
        get
        {
            return this.replicaField;
        }
        set
        {
            this.replicaField = value;
        }
    }
}